### ISSUE TITLE
User Doc has bad format

### ISSUE THREAD

**Issue by YinaZ** [PotatoTank/oratorio#13]
The User Doc looks bad and difficult to read because the margin is small.
## Expected Behavior

Decent margin and alignment that is easy to read.
## Current Behavior

Margin is nearly zero so the head of each line is stick to the edge of the page.
## Possible Solution

Add margins to the static file.
## Steps to Reproduce (for bugs)

Click User Doc on main page.

## Context

Looks visually unpleasant, but it should be easy to fix.
## Your Environment

* Version used: Master
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version: Mac OS X

**Comment by joeyli96** [comment]
Fixed in UI updates before Beta Release.
