### ISSUE TITLE
Stopping after pausing does not upload recording

### ISSUE THREAD

**Issue by logangirvin** [PotatoTank/oratorio#30]
## Expected Behavior

The smaller right stop button should stop the recording. 

## Current Behavior

It resets the recorder.

## Possible Solution

scripts.js file's event handler for the small right button on the recording being 'paused' is incorrectly set.

## Steps to Reproduce (for bugs)

1. Click record
2. Click pause
3. Click stop that appears after pause

## Context

We can't demo a perfect demo!

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version: linux, google chrome beta.

**Comment by YinaZ** [comment]
I just checked MediaStreamRecorder.js. Looks like the recorder won't do anything as long as it's "paused" (since resume() is not called yet). One thing we can do is to resume the recorder before stopping:

```
case "STOP":
    recorder.resume();
    recorder.stop();
    onStop(button, left, right);
    break;
```
