### ISSUE TITLE
Recording summary "stats bar" covers Logout Button

### ISSUE THREAD

**Issue by joeyli96** [PotatoTank/oratorio#36]
The statistics bar on the right side of the recording summary page covers the logout button.
## Expected Behavior

The logout button should not be covered.
## Current Behavior

The logout button is covered.
## Possible Solution

Shift the positioning of the button or the side bar, or change the z-index.
## Steps to Reproduce (for bugs)

1. Make recording and allow Oratorio to analyze it.
2. Notice that the Logout button is covered on the right side bar.
## Your Environment

* Version used: master
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version: Windows 10, Chrome

**Comment by logangirvin** [comment]
fixed in commit 1dfd1669c916fba823baeec7116d4fa42a458092
