### ISSUE TITLE
Spaces appearing in transcript after clicking on frequently-used words.

### ISSUE THREAD

**Issue by joeyli96** [PotatoTank/oratorio#54]
After clicking on frequently-used words (to highlight them in the transcript), spaces will appear in the transcript.
## Expected Behavior

Words should be highlighted but no modifications should be made to the transcript.
## Possible Solution

Look into how words are counted and parsed. Perhaps the splitting adds spaces.
## Steps to Reproduce (for bugs)

1. Record speech.
2. Look at transcript.
3. Click on a frequently-used word and see spaces appear in the transcript.

## Your Environment

* Version used: master
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version: Chrome on Windows 10

**Comment by dingoflamingo** [comment]
I fixed this in my branch

Root cause: The code was splitting the code over everything and appending the split text to the html

Changes: Changed to only split for spaces
