### ISSUE TITLE
Cannot scroll to the last item in sidebar

### ISSUE THREAD

**Issue by YinaZ** [PotatoTank/oratorio#65]
## Expected Behavior

scroll to the last item in sidebar and display it nicely

## Current Behavior

cannot scroll to the last item and can only see the top part of it

## Possible Solution

changes in css?

## Steps to Reproduce (for bugs)

populate the sidebar till you needs to scroll to see the last item

## Context

Cannot see the last item clearly

## Your Environment

* Version used: current master
* Environment name and version (e.g. Python 2.7):
* Operating System and version: Mac OS

**Comment by dingoflamingo** [comment]
fixed

root cause: did not account for top menu bar when resizing
